// cucumber.config.ts — optional CucumberJS CLI (primary runner: playwright-bdd + playwright test)
// Generated by playwright_generator_agent v1 (first run only).

import type { IConfiguration } from '@cucumber/cucumber';

const config: Partial<IConfiguration> = {
  paths: ['features/**/*.feature'],
  require: ['steps/**/*.steps.ts', 'fixtures/base.fixture.ts'],
  requireModule: ['ts-node/register'],
  format: [
    'progress-bar',
    'allure-cucumberjs/reporter',
    'json:cucumber-report.json',
  ],
  formatOptions: {
    resultsDir: 'allure-results',
  },
  worldParameters: {},
};

export default config;
