import * as fs from 'fs';
import * as path from 'path';

/**
 * Runs once before all tests: remove prior run artifacts so each execution starts clean.
 * Does not delete .features-gen (regenerated by bddgen before playwright test).
 */
export default async function globalSetup(): Promise<void> {
  const root = __dirname;
  const dirs = [
    'test-results',
    'allure-results',
    'playwright-report',
    'blob-report',
    'smart-reporter-output',
  ];
  for (const d of dirs) {
    const p = path.join(root, d);
    if (fs.existsSync(p)) {
      fs.rmSync(p, { recursive: true, force: true });
    }
  }
}
